### ISSUE TITLE
how to specify port for host?

### ISSUE THREAD

**Issue by karpa13st** [ak545/ssl-host-expiration-checker#1]
for example, i would monitor
https://example.com:444
how i can specify such definition in host file?

**Comment by ak545** [comment]
Please, try new version **0.1.5**.

Now you can set the port number in a text file, like this: **example.tld:444**
Or directly in the option, for example: **-o example.tld:444** or **--host example.tld:444**

If the port number is not specified, its default value will be **443**

**Comment by karpa13st** [comment]
Perfect!
works as expected
