### ISSUE TITLE
how to specify destination ip for checking?

### ISSUE THREAD

**Issue by karpa13st** [ak545/ssl-host-expiration-checker#2]
for example, we do not have a public hostname assigned to the monitoring host:
example.com is resolved to 127.0.0.1 or even not resolved et all
i would to configure host file like:
example.com 192.168.0.1

the expected result is - checker will connect to 192.168.0.1 and grab the expiration date for example.com

**Comment by ak545** [comment]
Typically, similar results are achieved by editing the local "**hosts**" file

If you have Linux OS, then: **/etc/hosts** (root rights are required to change the file)
If you have Windows OS, then: **C:\Windows\System32\drivers\etc\hosts** (Administrator rights are required to change the file)

The format and meaning of these files are almost the same in any OS's.
Here you can redefine IP addresses for domain names, for example:

`192.168.0.1 example.ltd`

With this value, the domain name **example.ltd** will refer to the IP address **192.168.0.1**

See: [https://en.wikipedia.org/wiki/Hosts_(file)](https://en.wikipedia.org/wiki/Hosts_(file))

**Comment by ak545** [comment]
And a small addition. If you will use the solution to the problem through hosts files, then when running my script, do not use the -g, --use-google-dns option. Otherwise, to resolve the domain name, the script will not use the local hosts file, but the Google NS server (8.8.8.8).
